const data = [
  {
    img: "https://res.cloudinary.com/jerrick/image/upload/d_642250b563292b35f27461a7.png,f_jpg,fl_progressive,q_auto,w_1024/620cfb997584c0001d7b6e77.png",
    title: "Suzuki GSX-R1000R",
    reviews: "(123 reviews)",
    prevPrice: "$149,999",
    newPrice: "$119,999",
    priceCategory : "4",
    company: "Suzuki",
    color: "grey",
    category: "sportsBike",
    description: "The Suzuki GSX-R1000R is a high-performance sports bike with advanced features.",
    power: "199 hp",
    weight: "443 lbs",
    size: "81.7 inches L x 28 inches W x 45.1 inches H",
    score:"4.9"
  },
  {
    img: "https://powersports.honda.com/-/media/products/family/xr650l/trims/trim-main/xr650l/2024/2024-xr650l-white-650x380.png",
    title: "Honda XR650L",
    reviews: "(123 reviews)",
    prevPrice: "$79,999",
    newPrice: "$69,999",
    priceCategory : "3",
    company: "Honda",
    color: "white",
    category: "dualSport",
    description: "The Honda XR650L is a versatile dual sport bike, perfect for both off-road and street riding.",
    power: "40 hp",
    weight: "346 lbs",
    size: "86.0 inches L x 33.9 inches W x 47.2 inches H",
    score:"3.8"
  },
  {
    img: "https://www.suzuki.ca/wp-content/uploads/VZR1800_Diagonal.jpg",
    title: "Suzuki BOULEVARD M109R",
    reviews: "(123 reviews)",
    prevPrice: "$169,999",
    newPrice: "$129,999",
    priceCategory : "4",
    company: "Suzuki",
    color: "black",
    category: "cruiser",
    description: "The Suzuki Boulevard M109R is a powerful cruiser bike known for its muscular design.",
    power: "128 hp",
    weight: "764 lbs",
    size: "97.6 inches L x 34.4 inches W x 44.7 inches H",
    score:"4.8"
  },
  {
    img: "https://www.harley-davidson.com/content/dam/h-d/images/product-images/bikes/motorcycle/2024/2024-road-glide-limited/2024-road-glide-limited-m13b/2024-road-glide-limited-m13b-motorcycle.jpg?impolicy=myresize&rw=500",
    title: "Harley Davidson ULTRA LIMITED™",
    reviews: "(123 reviews)",
    prevPrice: "$99,999",
    newPrice: "$79,999",
    priceCategory : "3",
    company: "HD",
    color: "blue",
    category: "touring",
    description: "The Harley Davidson Ultra Limited™ is a top-tier touring bike with premium features and comfort.",
    power: "114 hp",
    weight: "917 lbs",
    size: "102.4 inches L x 37.8 inches W x 56.7 inches H",
    score:"4.4"
  },
  {
    img: "https://cdn-fastly.motorcycle.com/media/2023/03/06/9048898/media.jpg?size=704x978&nocrop=1",
    title: "Suzuki standard",
    reviews: "(123 reviews)",
    prevPrice: "$39,999",
    newPrice: "$29,999",
    priceCategory : "2",
    company: "Suzuki",
    color: "black",
    category: "standard",
    description: "The Suzuki Standard is a reliable bike with a classic design and modern performance.",
    power: "75 hp",
    weight: "430 lbs",
    size: "83.1 inches L x 31.3 inches W x 45.5 inches H",
    score:"4.0"
  },
  {
    img: "https://cdn-jmpab.nitrocdn.com/XhrXbaxldbsWrCtSZaJTNtTOoIJgNehG/assets/images/optimized/rev-444aae6/mc.suzuki.com.ph/wp-content/uploads/elementor/thumbs/Burgman-Street-Standard-Candy-Red-qohmc62htqwf0vc5hhfplh97pb7q20g7lt7hwcx5vk.png",
    title: "Honda Scooter",
    reviews: "(123 reviews)",
    prevPrice: "$9,999",
    newPrice: "$8,999",
    priceCategory : "1",
    company: "Honda",
    color: "red",
    category: "Scooter",
    description: "The Honda Scooter is a convenient and efficient scooter ideal for city commuting.",
    power: "8.6 hp",
    weight: "234 lbs",
    size: "72.8 inches L x 28.5 inches W x 44.5 inches H",
    score:"1.4"
  },
]

export default data;
