const data = [
  {
    img: "https://www.motortrend.com/uploads/sites/10/2023/02/2023-mercedes-benz-gle-coupe-53-amg-4wd-suv-angular-front.png",
    title: "Mercedes GLA",
    reviews: "(123 reviews)",
    prevPrice: "$89,999",
    newPrice: "$69,999",
    priceCategory : "2",
    company: "Mercedes",
    color: "white",
    category: "SUV",
    description: "The Mercedes GLA is a luxurious and compact SUV offering a perfect blend of comfort and performance.",
    power: "221 hp",
    weight: "3,549 lbs",
    size: "173.6 inches L x 71 inches W x 63.5 inches H",
    score:"4.0"
  },
  {
    img: "https://i.pinimg.com/originals/38/96/b4/3896b41d4a0266beb024cc8b94d55128.jpg",
    title: "Ferrari Spider",
    reviews: "(123 reviews)",
    prevPrice: "$199,999",
    newPrice: "$149,999",
    priceCategory : "3",
    company: "Ferrari",
    color: "red",
    category: "sportsCar",
    description: "The Ferrari Spider is an epitome of speed and style, a dream car for sports car enthusiasts.",
    power: "710 hp",
    weight: "3,362 lbs",
    size: "179.1 inches L x 76.7 inches W x 47.8 inches H",
    score:"4.3"
  },
  {
    img: "https://i.pinimg.com/originals/26/26/8c/26268c68154966a3c35f6c9868267df0.png",
    title: "Lamborghini Veneno",
    reviews: "(123 reviews)",
    prevPrice: "$499,999",
    newPrice: "$399,999",
    priceCategory : "3",
    company: "Lamborghini",
    color: "white",
    category: "sportsCar",
    description: "The Lamborghini Veneno is an ultra-rare supercar known for its cutting-edge design and incredible performance.",
    power: "740 hp",
    weight: "3,285 lbs",
    size: "190.0 inches L x 82.7 inches W x 44.7 inches H",
    score:"4.7"
  },
  {
    img: "https://i.pinimg.com/736x/11/55/8c/11558c555a2e04ed5ed85f2385c9ec9c.jpg",
    title: "Bugatti Chiron",
    reviews: "(123 reviews)",
    prevPrice: "$3,999,999",
    newPrice: "$2,999,999",
    priceCategory : "4",
    company: "Bugatti",
    color: "blue",
    category: "sportsCar",
    description: "The Bugatti Chiron stands out as a symbol of luxury and power, featuring exceptional engineering and design.",
    power: "1,479 hp",
    weight: "4,400 lbs",
    size: "178.9 inches L x 80.2 inches W x 47.7 inches H",
    score:"5.0"
  },
  {
    img: "https://i.pinimg.com/736x/ac/e6/3b/ace63b2f6ccd29c7e567e070089fcd5b.jpg",
    title: "Bugatti Veyron",
    reviews: "(123 reviews)",
    prevPrice: "$1,999,999",
    newPrice: "$999,999",
    priceCategory : "4",
    company: "Bugatti",
    color: "black",
    category: "sportsCar",
    description: "The Bugatti Veyron is a masterpiece of automotive engineering, offering unparalleled speed and luxury.",
    power: "1,001 hp",
    weight: "4,162 lbs",
    size: "175.7 inches L x 78.7 inches W x 45.6 inches H",
    score:"4.5"
  },
  {
    img: "https://imgd.aeplcdn.com/370x208/n/p6fcuta_1509397.jpg?q=80",
    title: "BMW 2",
    reviews: "(123 reviews)",
    prevPrice: "$59,999",
    newPrice: "$39,999",
    priceCategory : "1",
    company: "BMW",
    color: "blue",
    category: "sedan",
    description: "The BMW 2 Series is a compact sedan that combines elegant design with impressive driving dynamics.",
    power: "228 hp",
    weight: "3,519 lbs",
    size: "178.5 inches L x 70.9 inches W x 55.9 inches H",
    score:"2.4"
  },
  {
    img: "https://i.pinimg.com/736x/e9/ce/f8/e9cef8a8414b2e2bea85b0c110e40b4f.jpg",
    title: "Mercedes GLC",
    reviews: "(123 reviews)",
    prevPrice: "$64,999",
    newPrice: "$44,999",
    priceCategory : "1",
    company: "Mercedes",
    color: "white",
    category: "SUV",
    description: "The Mercedes GLC is a mid-size luxury SUV known for its sophisticated design and advanced technology.",
    power: "255 hp",
    weight: "3,891 lbs",
    size: "183.3 inches L x 74.4 inches W x 64.5 inches H",
    score:"3.2"
  },
  {
    img: "https://di-uploads-pod6.dealerinspire.com/intercarinc/uploads/2017/06/2017-Mercedes-Benz-AMG-GT-Coupe.png",
    title: "Mercedes-AMG GT 4-door",
    reviews: "(123 reviews)",
    prevPrice: "$89,999",
    newPrice: "$69,999",
    priceCategory : "2",
    company: "Mercedes",
    color: "yellow",
    category: "coupe",
    description: "The Mercedes-AMG GT 4-door coupe combines sports car performance with four-door convenience and luxury.",
    power: "630 hp",
    weight: "4,530 lbs",
    size: "199.2 inches L x 76.9 inches W x 57.3 inches H",
    score:"3.7"
  },
  {
    img: "https://thumbs.dreamstime.com/b/exotic-super-car-laferrari-isolated-ferrari-supercar-black-driver-front-single-view-over-white-background-clipping-path-92632050.jpg",
    title: "Ferrari LaFerrari",
    reviews: "(123 reviews)",
    prevPrice: "$799,999",
    newPrice: "$599,999",
    priceCategory : "4",
    company: "Ferrari",
    color: "black",
    category: "hyper",
    description: "The Ferrari LaFerrari is a hybrid hypercar that showcases cutting-edge technology and breathtaking performance.",
    power: "950 hp",
    weight: "3,495 lbs",
    size: "185.1 inches L x 78.4 inches W x 43.9 inches H",
    score:"4.8"
  },
  {
    img: "https://i.pinimg.com/736x/fe/59/1b/fe591b2f728b3e39070499c2ef7d1cba.jpg",
    title: "Mercedes CLE Cabriolet",
    reviews: "(123 reviews)",
    prevPrice: "$74,999",
    newPrice: "$59,999",
    priceCategory : "2",
    company: "Mercedes",
    color: "white",
    category: "convertible",
    description: "The Mercedes CLE Cabriolet offers open-top driving pleasure combined with luxurious comfort and style.",
    power: "255 hp",
    weight: "3,858 lbs",
    size: "184.5 inches L x 73.9 inches W x 56.9 inches H",
    score:"1.9"
  },
];

export default data;
