const data = [
  {
    img: "https://bombardier.com/sites/default/files/2024-04/aircraft-challenger3500.png",
    title: "Bombardier Challenger 3500",
    reviews: "(123 reviews)",
    prevPrice: "$899,999",
    newPrice: "$849,999",
    priceCategory : "2",
    company: "Bombardier",
    color: "white",
    category: "privateJet",
    description: "The Bombardier Challenger 3500 is a luxurious private jet known for its comfort and advanced features.",
    power: "7,323 lbf thrust per engine",
    weight: "40,600 lbs",
    size: "68.5 ft L x 69 ft W x 20 ft H",
    score:"4.5"
  },
  {
    img: "https://bombardier.com/sites/default/files/2024-04/Global6500_silhouette_rightside_2.png",
    title: "Bombardier Challenger 6500",
    reviews: "(123 reviews)",
    prevPrice: "$1,599,999",
    newPrice: "$1,299,999",
    priceCategory : "3",
    company: "Bombardier",
    color: "white",
    category: "commercialJet",
    description: "The Bombardier Challenger 6500 is a commercial jet designed for long-range travel with superior performance.",
    power: "7,725 lbf thrust per engine",
    weight: "48,200 lbs",
    size: "99.4 ft L x 94 ft W x 25.5 ft H",
    score:"4.8"
  },
  {
    img: "https://thumbs.dreamstime.com/b/plane-white-background-7790806.jpg",
    title: "Airbus cargo plane",
    reviews: "(123 reviews)",
    prevPrice: "$6,999,999",
    newPrice: "$5,999,999",
    priceCategory : "4",
    company: "Airbus",
    color: "white",
    category: "cargo",
    description: "The Airbus cargo plane is designed for efficient cargo transport with high capacity and range.",
    power: "N/A",
    weight: "115,000 lbs",
    size: "124 ft L x 145 ft W x 43 ft H",
    score:"4.3"
  },
  {
    img: "https://pngimg.com/d/glider_PNG44.png",
    title: "Airbus glider",
    reviews: "(123 reviews)",
    prevPrice: "$199,999",
    newPrice: "$149,999",
    priceCategory : "1",
    company: "Airbus",
    color: "white",
    category: "glider",
    description: "The Airbus glider is engineered for smooth and silent flight, perfect for recreational soaring.",
    power: "N/A",
    weight: "1,500 lbs",
    size: "26 ft L x 55 ft W x 6 ft H",
    score:"3.0"
  },
  {
    img: "https://t4.ftcdn.net/jpg/06/05/69/83/360_F_605698300_3JAfqz1sD1x2ZKJAnSvR0K9CVyRO1Hdr.jpg",
    title: "G1 AVIATION seaplane",
    reviews: "(123 reviews)",
    prevPrice: "$499,999",
    newPrice: "$399,999",
    priceCategory : "1",
    company: "G1",
    color: "white",
    category: "seaPlane",
    description: "The G1 Aviation seaplane is ideal for water takeoffs and landings, offering versatility and adventure.",
    power: "180 hp",
    weight: "2,800 lbs",
    size: "34 ft L x 46 ft W x 12 ft H",
    score:"2.4"
  },
  {
    img: "https://png.pngtree.com/background/20231016/original/pngtree-a-3d-illustrated-white-background-featuring-a-civilian-helicopter-in-black-picture-image_5582340.jpg",
    title: "AgustaWestland helicopter",
    reviews: "(123 reviews)",
    prevPrice: "$299,999",
    newPrice: "$199,999",
    priceCategory : "1",
    company: "AgustaWestland",
    color: "yellow",
    category: "helicopter",
    description: "The AgustaWestland helicopter is known for its reliability and performance, suitable for various missions.",
    power: "1,100 hp per engine",
    weight: "10,000 lbs",
    size: "42 ft L x 36 ft W x 14 ft H",
    score:"4.4"
  }
];

export default data;
